name = "clarke-chronicles"
compatibility_date = "2026-08-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "clarke-chronicles-leaderboard"
database_id = "567bd0f0-545b-44a3-a698-372063bc430e"
